export const GET_FLASHCARDS = "GET_FLASHCARDS";
export const GET_FLASHCARDS_BY_CATEGORY = "GET_FLASHCARDS_BY_CATEGORY";

export const GET_FLASHCARDS_BY_CATEGORY_AND_DIFFICULTY =
  "GET_FLASHCARDS_BY_CATEGORY_AND_DIFFICULTY";

export const GET_CATEGORIES = "GET_CATEGORIES";

export const GET_COUNT_ALL_FLASHCARDS = "GET_COUNT_ALL_FLASHCARDS";
export const GET_COUNT_ALL_FLASHCARDS_BY_KNOWLEDGE =
  "GET_COUNT_ALL_FLASHCARDS_BY_KNOWLEDGE";

export const GET_COUNT_ALL_FLASHCARDS_BY_CATEGORY =
  "GET_COUNT_ALL_FLASHCARDS_BY_CATEGORY";

export const GET_COUNT_ALL_FLASHCARDS_BY_CATEGORY_AND_KNOWLEDGE =
  "GET_COUNT_ALL_FLASHCARDS_BY_CATEGORY_AND_KNOWLEDGE";

export const DELETE_FLASHCARD = "DELETE_FLASHCARD";

export const GET_FLASHCARD = "GET_FLASHCARD";

export const GET_ERRORS = "GET_ERRORS";

export const GET_RANDOM_FLASHCARDS = "GET_RANDOM_FLASHCARDS";
