export const GET_NOT_ACCEPTED_FLASHCARDS = "GET_NOT_ACCEPTED_FLASHCARDS";
export const GET_ACCEPTED_FLASHCARDS = "GET_ACCEPTED_FLASHCARDS";
export const GET_FLASHCARDS_BY_CATEGORY = "GET_FLASHCARDS_BY_CATEGORY";

export const GET_FLASHCARDS_BY_CATEGORY_AND_DIFFICULTY =
  "GET_FLASHCARDS_BY_CATEGORY_AND_DIFFICULTY";

export const GET_CATEGORIES = "GET_CATEGORIES";

export const GET_COUNT_ALL_FLASHCARDS = "GET_COUNT_ALL_FLASHCARDS";
export const GET_COUNT_ALL_FLASHCARDS_BY_KNOWLEDGE =
  "GET_COUNT_ALL_FLASHCARDS_BY_KNOWLEDGE";

export const GET_COUNT_ALL_FLASHCARDS_BY_CATEGORY =
  "GET_COUNT_ALL_FLASHCARDS_BY_CATEGORY";

export const GET_COUNT_ALL_FLASHCARDS_BY_CATEGORY_AND_KNOWLEDGE =
  "GET_COUNT_ALL_FLASHCARDS_BY_CATEGORY_AND_KNOWLEDGE";

export const DELETE_FLASHCARD = "DELETE_FLASHCARD";

export const GET_FLASHCARD = "GET_FLASHCARD";

export const GET_ERRORS = "GET_ERRORS";

export const GET_RANDOM_FLASHCARDS = "GET_RANDOM_FLASHCARDS";

export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const ACCEPT_FLASHCARD = "ACCEPT_FLASHCARD";

export const REJECT_FLASHCARD = "REJECT_FLASHCARD";

export const GET_ALL_TICKETS = "GET_ALL_TICKETS";

export const DELETE_TICKET = "DELETE_TICKET";

export const GET_TICKET = "GET_TICKET";
